# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/c3ma/Development/fullcircle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/c3ma/Development/fullcircle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/c3ma/Development/fullcircle/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/c3ma/Development/fullcircle/CMakeFiles /home/c3ma/Development/fullcircle/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/c3ma/Development/fullcircle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fc-2gif

# Build rule for target.
fc-2gif: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-2gif
.PHONY : fc-2gif

# fast build rule for target.
fc-2gif/fast:
	$(MAKE) -f src/CMakeFiles/fc-2gif.dir/build.make src/CMakeFiles/fc-2gif.dir/build
.PHONY : fc-2gif/fast

#=============================================================================
# Target rules for targets named fc-add

# Build rule for target.
fc-add: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-add
.PHONY : fc-add

# fast build rule for target.
fc-add/fast:
	$(MAKE) -f src/CMakeFiles/fc-add.dir/build.make src/CMakeFiles/fc-add.dir/build
.PHONY : fc-add/fast

#=============================================================================
# Target rules for targets named fc-badge

# Build rule for target.
fc-badge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-badge
.PHONY : fc-badge

# fast build rule for target.
fc-badge/fast:
	$(MAKE) -f src/CMakeFiles/fc-badge.dir/build.make src/CMakeFiles/fc-badge.dir/build
.PHONY : fc-badge/fast

#=============================================================================
# Target rules for targets named fc-concat

# Build rule for target.
fc-concat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-concat
.PHONY : fc-concat

# fast build rule for target.
fc-concat/fast:
	$(MAKE) -f src/CMakeFiles/fc-concat.dir/build.make src/CMakeFiles/fc-concat.dir/build
.PHONY : fc-concat/fast

#=============================================================================
# Target rules for targets named fc-demo

# Build rule for target.
fc-demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-demo
.PHONY : fc-demo

# fast build rule for target.
fc-demo/fast:
	$(MAKE) -f src/CMakeFiles/fc-demo.dir/build.make src/CMakeFiles/fc-demo.dir/build
.PHONY : fc-demo/fast

#=============================================================================
# Target rules for targets named fc-flowmap

# Build rule for target.
fc-flowmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-flowmap
.PHONY : fc-flowmap

# fast build rule for target.
fc-flowmap/fast:
	$(MAKE) -f src/CMakeFiles/fc-flowmap.dir/build.make src/CMakeFiles/fc-flowmap.dir/build
.PHONY : fc-flowmap/fast

#=============================================================================
# Target rules for targets named fc-getid

# Build rule for target.
fc-getid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-getid
.PHONY : fc-getid

# fast build rule for target.
fc-getid/fast:
	$(MAKE) -f src/CMakeFiles/fc-getid.dir/build.make src/CMakeFiles/fc-getid.dir/build
.PHONY : fc-getid/fast

#=============================================================================
# Target rules for targets named fc-gol

# Build rule for target.
fc-gol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-gol
.PHONY : fc-gol

# fast build rule for target.
fc-gol/fast:
	$(MAKE) -f src/CMakeFiles/fc-gol.dir/build.make src/CMakeFiles/fc-gol.dir/build
.PHONY : fc-gol/fast

#=============================================================================
# Target rules for targets named fc-leader

# Build rule for target.
fc-leader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-leader
.PHONY : fc-leader

# fast build rule for target.
fc-leader/fast:
	$(MAKE) -f src/CMakeFiles/fc-leader.dir/build.make src/CMakeFiles/fc-leader.dir/build
.PHONY : fc-leader/fast

#=============================================================================
# Target rules for targets named fc-perlin

# Build rule for target.
fc-perlin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-perlin
.PHONY : fc-perlin

# fast build rule for target.
fc-perlin/fast:
	$(MAKE) -f src/CMakeFiles/fc-perlin.dir/build.make src/CMakeFiles/fc-perlin.dir/build
.PHONY : fc-perlin/fast

#=============================================================================
# Target rules for targets named fc-ping

# Build rule for target.
fc-ping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-ping
.PHONY : fc-ping

# fast build rule for target.
fc-ping/fast:
	$(MAKE) -f src/CMakeFiles/fc-ping.dir/build.make src/CMakeFiles/fc-ping.dir/build
.PHONY : fc-ping/fast

#=============================================================================
# Target rules for targets named fc-player

# Build rule for target.
fc-player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-player
.PHONY : fc-player

# fast build rule for target.
fc-player/fast:
	$(MAKE) -f src/CMakeFiles/fc-player.dir/build.make src/CMakeFiles/fc-player.dir/build
.PHONY : fc-player/fast

#=============================================================================
# Target rules for targets named fc-read-image

# Build rule for target.
fc-read-image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-read-image
.PHONY : fc-read-image

# fast build rule for target.
fc-read-image/fast:
	$(MAKE) -f src/CMakeFiles/fc-read-image.dir/build.make src/CMakeFiles/fc-read-image.dir/build
.PHONY : fc-read-image/fast

#=============================================================================
# Target rules for targets named fc-server

# Build rule for target.
fc-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-server
.PHONY : fc-server

# fast build rule for target.
fc-server/fast:
	$(MAKE) -f src/CMakeFiles/fc-server.dir/build.make src/CMakeFiles/fc-server.dir/build
.PHONY : fc-server/fast

#=============================================================================
# Target rules for targets named fc-simulator

# Build rule for target.
fc-simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-simulator
.PHONY : fc-simulator

# fast build rule for target.
fc-simulator/fast:
	$(MAKE) -f src/CMakeFiles/fc-simulator.dir/build.make src/CMakeFiles/fc-simulator.dir/build
.PHONY : fc-simulator/fast

#=============================================================================
# Target rules for targets named fc-testimage

# Build rule for target.
fc-testimage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-testimage
.PHONY : fc-testimage

# fast build rule for target.
fc-testimage/fast:
	$(MAKE) -f src/CMakeFiles/fc-testimage.dir/build.make src/CMakeFiles/fc-testimage.dir/build
.PHONY : fc-testimage/fast

#=============================================================================
# Target rules for targets named fc-testrow

# Build rule for target.
fc-testrow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-testrow
.PHONY : fc-testrow

# fast build rule for target.
fc-testrow/fast:
	$(MAKE) -f src/CMakeFiles/fc-testrow.dir/build.make src/CMakeFiles/fc-testrow.dir/build
.PHONY : fc-testrow/fast

#=============================================================================
# Target rules for targets named fc-text

# Build rule for target.
fc-text: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-text
.PHONY : fc-text

# fast build rule for target.
fc-text/fast:
	$(MAKE) -f src/CMakeFiles/fc-text.dir/build.make src/CMakeFiles/fc-text.dir/build
.PHONY : fc-text/fast

#=============================================================================
# Target rules for targets named fullcircle

# Build rule for target.
fullcircle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fullcircle
.PHONY : fullcircle

# fast build rule for target.
fullcircle/fast:
	$(MAKE) -f libfullcircle/CMakeFiles/fullcircle.dir/build.make libfullcircle/CMakeFiles/fullcircle.dir/build
.PHONY : fullcircle/fast

#=============================================================================
# Target rules for targets named sequencetest

# Build rule for target.
sequencetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sequencetest
.PHONY : sequencetest

# fast build rule for target.
sequencetest/fast:
	$(MAKE) -f tests/sequences/CMakeFiles/sequencetest.dir/build.make tests/sequences/CMakeFiles/sequencetest.dir/build
.PHONY : sequencetest/fast

#=============================================================================
# Target rules for targets named fillframetest

# Build rule for target.
fillframetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fillframetest
.PHONY : fillframetest

# fast build rule for target.
fillframetest/fast:
	$(MAKE) -f tests/frame/CMakeFiles/fillframetest.dir/build.make tests/frame/CMakeFiles/fillframetest.dir/build
.PHONY : fillframetest/fast

#=============================================================================
# Target rules for targets named fontstest

# Build rule for target.
fontstest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fontstest
.PHONY : fontstest

# fast build rule for target.
fontstest/fast:
	$(MAKE) -f tests/fonts/CMakeFiles/fontstest.dir/build.make tests/fonts/CMakeFiles/fontstest.dir/build
.PHONY : fontstest/fast

#=============================================================================
# Target rules for targets named spritestest

# Build rule for target.
spritestest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spritestest
.PHONY : spritestest

# fast build rule for target.
spritestest/fast:
	$(MAKE) -f tests/sprites/CMakeFiles/spritestest.dir/build.make tests/sprites/CMakeFiles/spritestest.dir/build
.PHONY : spritestest/fast

#=============================================================================
# Target rules for targets named config_filestest

# Build rule for target.
config_filestest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config_filestest
.PHONY : config_filestest

# fast build rule for target.
config_filestest/fast:
	$(MAKE) -f tests/configfile/CMakeFiles/config_filestest.dir/build.make tests/configfile/CMakeFiles/config_filestest.dir/build
.PHONY : config_filestest/fast

#=============================================================================
# Target rules for targets named flowmaptest

# Build rule for target.
flowmaptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flowmaptest
.PHONY : flowmaptest

# fast build rule for target.
flowmaptest/fast:
	$(MAKE) -f tests/flow_map/CMakeFiles/flowmaptest.dir/build.make tests/flow_map/CMakeFiles/flowmaptest.dir/build
.PHONY : flowmaptest/fast

#=============================================================================
# Target rules for targets named nettest

# Build rule for target.
nettest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nettest
.PHONY : nettest

# fast build rule for target.
nettest/fast:
	$(MAKE) -f tests/net/CMakeFiles/nettest.dir/build.make tests/net/CMakeFiles/nettest.dir/build
.PHONY : nettest/fast

#=============================================================================
# Target rules for targets named fc-bml2fcs

# Build rule for target.
fc-bml2fcs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc-bml2fcs
.PHONY : fc-bml2fcs

# fast build rule for target.
fc-bml2fcs/fast:
	$(MAKE) -f bml2fcs/CMakeFiles/fc-bml2fcs.dir/build.make bml2fcs/CMakeFiles/fc-bml2fcs.dir/build
.PHONY : fc-bml2fcs/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... fc-2gif"
	@echo "... fc-add"
	@echo "... fc-badge"
	@echo "... fc-concat"
	@echo "... fc-demo"
	@echo "... fc-flowmap"
	@echo "... fc-getid"
	@echo "... fc-gol"
	@echo "... fc-leader"
	@echo "... fc-perlin"
	@echo "... fc-ping"
	@echo "... fc-player"
	@echo "... fc-read-image"
	@echo "... fc-server"
	@echo "... fc-simulator"
	@echo "... fc-testimage"
	@echo "... fc-testrow"
	@echo "... fc-text"
	@echo "... fullcircle"
	@echo "... sequencetest"
	@echo "... fillframetest"
	@echo "... fontstest"
	@echo "... spritestest"
	@echo "... config_filestest"
	@echo "... flowmaptest"
	@echo "... nettest"
	@echo "... fc-bml2fcs"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

